<?php

namespace Hl\Testtalk\HlTesttalkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
    public function findAllBooks(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT book FROM HlTesttalkHlTesttalkBundle:Book book ORDER BY book.id ASC')
                ->getResult();
    }
}
